#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

source ${OPENSHIFT_DEPENDENCIES_DIR}python/bin/activate
date >> ${OPENSHIFT_LOG_DIR}/mosesserver.log
nohup python3 ${OPENSHIFT_REPO_DIR}diy/mosesserver.py >> ${OPENSHIFT_LOG_DIR}/mosesserver.log 2>&1 &
echo Caching model files...
cat ${OPENSHIFT_DATA_DIR}zhc2zhm/* > /dev/null
cat ${OPENSHIFT_DATA_DIR}zhm2zhc/* > /dev/null
python3 ${OPENSHIFT_REPO_DIR}diy/speedestimate.py
echo Waiting for server...
n=0
until [ $n -ge 3 ]
do
  python3 ${OPENSHIFT_REPO_DIR}diy/mosesproxy.py ping
  rc=$?
  [ $rc -eq 0 ] && break
  n=$[$n+1]
  echo "Retry and wait... $n"
  sleep 5
done
if [ $rc -ne 0 ] ; then
  exit $rc
fi

# Stop the 503 server
SREVPROC="$(ps -ef | grep 503server.py | grep -v grep)"
if [ ! -z "$SREVPROC" ]; then
  kill `echo "$SREVPROC" | awk '{ print $2 }'`
  sleep 1
fi

rm ${OPENSHIFT_TMP_DIR}uwsgi.pid
${OPENSHIFT_DATA_DIR}bin/uwsgi --ini ${OPENSHIFT_REPO_DIR}uwsgi.ini
