#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
source ${OPENSHIFT_DEPENDENCIES_DIR}python/bin/activate
rm ${OPENSHIFT_TMP_DIR}uwsgi.pid
${OPENSHIFT_DATA_DIR}bin/uwsgi --ini ${OPENSHIFT_REPO_DIR}uwsgi.ini
